[advisories]
yanked = "deny"
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
]
confidence-threshold = 0.8
exceptions = []
private = { ignore = true }

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
